### ISSUE TITLE
CloudFile path is not consistent

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#85] opened 2015-05-26 22:02 UTC
This is what I think is inconsistent behaviour: -

```fsharp
let path = "data/myfile.txt"
let cf = CloudFile path
let cfPath = cf.Path // myfile.txt - container is missing now
let exists = CloudFile.Exists cfPath |> cluster.Run // throws System.ArgumentException: Illegal characters in path
let size = cf.Size |> cluster.RunLocally // System.Exception: Invalid container ''
```

Indeed if I navigate to the file via ```CloudFile.Enumerate "data```, I get a file whose path is ```\datamyfile.txt"```. It still fails on the call to Size etc..

This is on 0.6.8.

**Comment by eiriktsarpalis** [comment] 2015-05-26 22:22
I'm actually surprised with line 3. CloudFile is just a dumb wrapper for string, it won't change, check or normalise the path in any way, even if it's garbage. That said, I think that the exception messages in MBrace.Azure could be clearer, probably InvalidPathException or FileNotFoundException. 

Also, the behaviour of CloudFile.Enumerate sounds like a bug.

**Comment by krontogiannis** [comment] 2015-05-26 22:50
I can't reproduce this.

```fsharp
let path = "data/myfile.txt"
runtime.StoreClient.File.WriteAllText(path, "foo") |> ignore

let cf = CloudFile path
let cfPath = cf.Path // data/myfile.txt
let exists = CloudFile.Exists cfPath 
             |> runtime.RunLocally // true
let size = cf.Size 
            |> runtime.RunLocally // 3
```

**Comment by isaacabraham** [comment] 2015-05-27 07:31
Ok. Let me try to repro on my laptop later today - if I can't it's something on my PC that is wrong.
________________________________

**Comment by dsyme** [comment] 2015-07-25 00:11
@isaacabraham did you get a chance to check this?

Closing this since @krontogiannis checked it as was definite this couldn't be happening :)

**Closed by dsyme** 2015-07-25 00:11 UTC

**Comment by isaacabraham** [comment] 2015-07-25 10:01
Happy to close - will try to repro and reopen if necessary
