### ISSUE TITLE
Provide details on provisioning: VM sizes

### ISSUE THREAD

**Issue by evilpepperman** [mbraceproject/MBrace.Azure#131] opened 2015-11-30 21:22 UTC
I notice that the default VM size in the tutorial is `Large`.  In order to lower costs, I would like to know the smallest usable VM for `CloudFlow` operations.  I tried once or twice (under `alpha-0.16`) to provision `Small`, and the cluster never got created.  Maybe I was just impatient.

Please provide some details on minimum cluster parameters (i.e. minimum # of VM, minimum VM size).

Also, please explain if *IaaS* Virtual Machines are used, or just Cloud Services.  I saw a mention of *IaaS* in http://lenadroid.github.io/posts/fsharp-cloud-monads-part-2.html , so I want to be sure I am presenting the services and costs accurately.

**Comment by eiriktsarpalis** [comment] 2015-11-30 22:40
Have you tried doing the same with MBrace.Azure >= 1.1? There were a few issues regarding vm compatibility in previous releases.

By default we do not deploy using IaaS VMs although it is possible to create those by hand. Also, I should note that the linked blog post is very outdated.

**Comment by isaacabraham** [comment] 2015-11-30 22:48
Theoretically I think that you should be able to provision Small VMs onwards (although I really wouldn't recommend anything less than Medium - the performance of Small and less is dreadful).

MBrace.Azure can be run as plain IAAS VMs - indeed the original incarnation of MBrace used this model solely - which I suspect is what is referred to in that blog post - but MBrace.Azure can run both as a "plain exe" (which could run on a VM in an IAAS model) and also as a Cloud Service (and this is the model that is currently recommended through the Starter Kit). The latter is also available in raw form in MBrace.Azure as a Cloud Service project for you to modify as you see fit.

In terms of costing, Cloud Services and raw VMs in Azure cost the same AFAIK so there should be no difference there.

Note that irrespective of deployment model, in addition to the compute costs of VM / Cloud Service, MBrace.Azure also make use of Service Bus and Storage, whose costs (whilst low) also should be factored in.

**Comment by evilpepperman** [comment] 2015-11-30 22:54
Thanks for the color @isaacabraham !  I read your notes with great interest.

@eiriktsarpalis I will try this again as soon as I get my provisioning working again.  And, yeah, it's an old post, but someone showed it to me, so I (as the "expert") had to follow that thread.

**Comment by isaacabraham** [comment] 2016-02-10 01:55
I'm closing this issue as a duplicate of #133. Small and Extra Small currently don't provision as (I believe) the disk space requirements of MBrace have been set too high. #141 will at least surface this error if you select one of those VM sizes though.

**Closed by isaacabraham** 2016-02-10 01:55 UTC
Labels: discussion, question
